from setuptools import setup, find_packages

setup(
    name="007-osint-tool",
    version="1.0.0",
    description="Outil OSINT multifonction (Discord, IP, scraping, analyse, etc.)",
    author="KRATORAK",
    packages=find_packages(),
    install_requires=[
        "requests",
        "colorama",
        "beautifulsoup4",
        "lxml",
        "python-whois",
        "ipwhois",
        "shodan",
        "virustotal-python",
        "geopy",
        "folium",
        "matplotlib",
        "pandas",
        "Pillow",
        "discord-webhook",
        "dnspython",
        "opencv-python",
        "nmap",
        "thefuzz",
        "rich",
        "textblob",
        "pytesseract",
    ],
    python_requires=">=3.8",
)
